services:
  alltalk-tts:
    build:
      context: .
      dockerfile: Dockerfile-amd
    image: alltalk_tts:rocm-5.7
    restart: unless-stopped
    ports:
      - "7851:7851"
    container_name: alltalk-tts
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    command: "/bin/bash"
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 8G
    volumes:
      - ./outputs:/app/outputs/
      - ./models:/app/models/
      - ./voices:/app/voices/
      - ./finetune/put-voice-samples-in-here:/app/finetune/put-voice-samples-in-here
      - ./dockerconfig.json:/app/confignew.json